# Generated by Django 2.2.4 on 2022-05-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domino_pic', models.FileField(upload_to='dominoscan/images')),
                ('top_half', models.IntegerField(null=True)),
                ('bottom_half', models.IntegerField(null=True)),
            ],
        ),
    ]
